In [3]:
import pandas as pd
import numpy as np 

np.random.seed(1)  # pseudo random number generator

In [4]:
no_samples = 1000
no_class0_ratio = 0.9
no_class_0 = int(no_samples*no_class0_ratio)
no_class_1 = 100

no_class_0,no_class_1

(900, 100)

In [6]:
class_0 = {"feature0":np.random.normal(0,1,no_class_0),
"feature1":np.random.normal(0,1,no_class_0),
"target": [0]*no_class_0
}
df = pd.DataFrame(class_0)
df

     feature0  feature1  target
0   -1.307971 -0.453503       0
1    1.472396 -0.820905       0
2    0.074876  0.940219       0
3   -1.786935 -1.411293       0
4    0.165211  0.884148       0
..        ...       ...     ...
895 -1.322762 -1.140488       0
896  0.540306  0.501016       0
897 -0.507257  0.225767       0
898  1.128379 -1.089087       0
899 -1.223351  1.280058       0

[900 rows x 3 columns]

In [7]:
class_1 = {"feature0":np.random.normal(3,1,no_class_1),
"feature1":np.random.normal(3,1,no_class_1),
"target": [1]*no_class_1
}
df1 = pd.DataFrame(class_1)

In [8]:
data = pd.concat([df,df1]).reset_index(drop=True)
data

     feature0  feature1  target
0   -1.307971 -0.453503       0
1    1.472396 -0.820905       0
2    0.074876  0.940219       0
3   -1.786935 -1.411293       0
4    0.165211  0.884148       0
..        ...       ...     ...
995  2.247285  4.236735       1
996  4.360377  4.116299       1
997  3.386375  3.675240       1
998  3.388515  3.022452       1
999  3.030522  2.128963       1

[1000 rows x 3 columns]

In [23]:
data.target.value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [ ]:
# up sampling means to repeat the minority class data

In [26]:
data_majority = data[data.target == 0]

In [27]:
data_minority = data[data.target == 1]

In [29]:
# replace - if replace is true then -> it means data will be repeated 
from sklearn.utils import resample
data_minority_upsampled = resample(data_minority,replace=True,n_samples =len(data_majority),random_state=1)

In [31]:
data_minority_upsampled.shape

(900, 3)

In [40]:
data_upsampled = pd.concat([data_majority,data_minority_upsampled])
data_upsampled.target.value_counts()

target
0    900
1    900
Name: count, dtype: int64

In [41]:
# DOWN SAMPLING

In [47]:
data_majority_down_sampling = resample(data_majority,replace=False,n_samples=len(data_minority),random_state=1)

In [48]:
data_majority_down_sampling

     feature0  feature1  target
860 -1.537535  0.122837       0
880 -0.838450 -1.586623       0
874 -0.771039 -1.448482       0
780 -2.018355  0.502019       0
525 -0.521316  0.452069       0
..        ...       ...     ...
494  1.152007  0.781319       0
255 -0.241664  0.297858       0
672 -0.999110 -0.053589       0
481 -0.080607 -0.644226       0
838 -0.193112  0.058194       0

[100 rows x 3 columns]