In [165]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt
import seaborn as sns 

import warnings 
warnings.filterwarnings("ignore")

In [166]:
from sklearn.datasets import make_classification

In [167]:
x , y = make_classification(n_samples=1000,n_features=20,n_classes=2,random_state=1)

In [168]:
x

array([[-2.04582165, -0.13791624, -0.08071423, ...,  2.48194524,
         0.74236675,  0.23154789],
       [-0.98726024,  1.30120189,  2.37734888, ...,  0.55445754,
        -0.21892143, -0.37608578],
       [ 0.57335921,  0.09375582,  0.4662521 , ..., -0.6088508 ,
         0.79903499, -0.17121177],
       ...,
       [-0.70737159,  1.07650943,  0.58510456, ..., -1.51337602,
         0.90239871, -0.69230951],
       [-0.20706849,  1.17319848, -1.94478665, ..., -0.32820676,
         1.5711921 ,  1.14877729],
       [-2.16769231, -2.54871672,  2.89359255, ...,  0.71535366,
         0.34329241,  1.07350284]])

In [169]:
y

array([0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0,
       1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1,
       0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1,
       0, 0, 1, 1, 0, 1, 0, 1, 1, 0])

In [170]:
from sklearn.model_selection import train_test_split

In [171]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.30,random_state=1)

In [172]:
# custome baggingclassifier  - > heterogenous parallel model are built

In [173]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB

In [174]:
lr_clf = LogisticRegression()
dt_clf = DecisionTreeClassifier()
sv_clf = SVC()
nb_clf = GaussianNB()

In [175]:
# ensembles technique 
from sklearn.ensemble import VotingClassifier

In [176]:
ensemble_clf = VotingClassifier(estimators=[("log_reg",lr_clf),("dec_classifier",dt_clf),("support_vec",sv_clf),("naive_bais",nb_clf)],voting="hard")

In [177]:
ensemble_clf.fit(x_train,y_train)

VotingClassifier(estimators=[('log_reg', LogisticRegression()),
                             ('dec_classifier', DecisionTreeClassifier()),
                             ('support_vec', SVC()),
                             ('naive_bais', GaussianNB())])

In [178]:
y_pred = ensemble_clf.predict(x_test)

In [179]:
from sklearn.metrics import accuracy_score

In [180]:
accuracy_score(y_test , y_pred)

0.8566666666666667

In [181]:
## custom bagging regressor

In [182]:
from sklearn.datasets import make_regression

In [183]:
from sklearn.model_selection import train_test_split

In [184]:
x , y = make_regression(n_samples=1000,n_features=10,noise=0.1,random_state=1)

In [185]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.20,random_state=1)

In [186]:
from sklearn.linear_model import LinearRegression
from sklearn.svm import  SVR
from sklearn.tree import DecisionTreeRegressor

In [187]:
dt_reg = DecisionTreeRegressor()
sv_reg = SVR(kernel="linear")
lr_reg = LinearRegression()

In [188]:
from sklearn.ensemble import VotingRegressor

In [189]:
ensemble_reg = VotingRegressor(estimators=[("decison_reg",dt_reg),("support_reg",sv_reg),("linear_reg",lr_reg)])

In [190]:
ensemble_reg.fit(x_train,y_train)

VotingRegressor(estimators=[('decison_reg', DecisionTreeRegressor()),
                            ('support_reg', SVR(kernel='linear')),
                            ('linear_reg', LinearRegression())])

In [191]:
y_pred = ensemble_reg.predict(x_test)

In [192]:
from sklearn.metrics import r2_score

In [193]:
r2_score(y_test,y_pred)

0.9521028656052704

In [194]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

import warnings 
warnings.filterwarnings("ignore")

In [195]:
# multiple model training , pipeline , and column transform

In [196]:
df = sns.load_dataset("tips")

In [197]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [198]:
#  ENGIST THE DATA (READ THE DATA)  --> EDA --> x, y --> traintest split --> model_training

In [199]:
# what is the time ? if anyone visiting their is lunch or dinner

In [200]:
# EDA (SUBJECTIVE)

# DATA PREP --> ENCODING , MISSING VALUE TREAT , SCALING

In [201]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

In [202]:
df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [203]:
# we use label encoder 
from sklearn.preprocessing import LabelEncoder

In [204]:
le = LabelEncoder()

In [205]:
ans = le.fit_transform(df["time"])

In [206]:
df["time"] = ans

In [207]:
x = df.drop("time",axis=1)

In [208]:
y = df["time"]

In [209]:
from sklearn.model_selection import train_test_split

In [210]:
x_train , x_test , y_train , y_test = train_test_split(x,y ,test_size=0.2,random_state=1)

In [211]:
from sklearn.impute import SimpleImputer # for missing value treatment 
from sklearn.preprocessing import OneHotEncoder # for encoding
from sklearn.preprocessing import StandardScaler  # for scaling

In [212]:
from sklearn.pipeline import Pipeline  # a sequesnce of data transformer 
from sklearn.compose import ColumnTransformer # group all the pipeline steps to all the columns

In [213]:
df.sample(1)

    total_bill   tip   sex smoker  day  time  size
48       28.55  2.05  Male     No  Sun     0     3

In [214]:
num_cols = ["total_bill","tip","size"]
cat_cols = ["sex","smoker","day"]

In [215]:
num_pipeline = Pipeline(steps=[("imputation",SimpleImputer(strategy="median")),("scaling",StandardScaler())])

In [216]:
cat_pipeline = Pipeline(steps=[("imputation",SimpleImputer(strategy="most_frequent")),("encoding",OneHotEncoder())])

In [217]:
preprosser = ColumnTransformer([("num_pipeline",num_pipeline,num_cols),("cat_pipeline",cat_pipeline,cat_cols)])

In [218]:
x_train = preprosser.fit_transform(x_train)
x_test = preprosser.transform(x_test)

In [221]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

In [223]:
model = {"logisticreg":LogisticRegression(),"supportvector":SVC(),"decisiontree":DecisionTreeClassifier()}

In [230]:
for i in range(len(model)):
    print(list(model.values())[i])

LogisticRegression()
SVC()
DecisionTreeClassifier()

In [235]:
from sklearn.metrics import accuracy_score

def model_train_evaluation(x_train,x_test,y_train,y_test,model):
    evaluation = {}
    for i in range(len(model)):
        models = list(model.values())[i]
        models.fit(x_train,y_train)
        y_pred = models.predict(x_test)
        model_score = accuracy_score(y_test,y_pred)
        evaluation[list(model.keys())[i]] = model_score
    return evaluation

In [236]:
model_train_evaluation(x_train,x_test,y_train,y_test,model)

{'logisticreg': 0.9183673469387755,
 'supportvector': 0.9183673469387755,
 'decisiontree': 0.9387755102040817}