In [3]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [5]:
import pandas as pd 
df= pd.DataFrame({'result':['good','bad','good','bad','excellent','bad','excellent','good','bad']})
df

      result
0       good
1        bad
2       good
3        bad
4  excellent
5        bad
6  excellent
7       good
8        bad

In [7]:
df.result.value_counts()

result
bad          4
good         3
excellent    2
Name: count, dtype: int64

In [9]:
# fit , transform , and fit_transform 
le.fit(df.loc[:,'result'])

LabelEncoder()

In [11]:
ans = le.transform(df.loc[:,"result"])

In [13]:
df.loc[:,"new"] = ans

In [17]:
df.value_counts()

result     new
bad        0      4
good       2      3
excellent  1      2
Name: count, dtype: int64

In [21]:
# we can also do directly fit_transform 
encoder = LabelEncoder()
ans2 = encoder.fit_transform(df.loc[:,"result"])

In [ ]:
df.loc[:,"new1"] = ans2   # meaning of one hpt encoder 
df

      result  new  new1  result_bad  result_excellent  result_good
0       good    2     2         0.0               0.0          1.0
1        bad    0     0         1.0               0.0          0.0
2       good    2     2         0.0               0.0          1.0
3        bad    0     0         1.0               0.0          0.0
4  excellent    1     1         0.0               1.0          0.0
5        bad    0     0         1.0               0.0          0.0
6  excellent    1     1         0.0               1.0          0.0
7       good    2     2         0.0               0.0          1.0
8        bad    0     0         1.0               0.0          0.0

In [29]:
from sklearn.preprocessing import OneHotEncoder
onehot = OneHotEncoder()

In [33]:
onehot.fit(df.loc[:,["result"]])

OneHotEncoder()

In [ ]:
answ = onehot.transform(df.loc[:,["result"]]).toarray()  # why this array is used

In [44]:
onehot.get_feature_names_out()

array(['result_bad', 'result_excellent', 'result_good'], dtype=object)

In [52]:
df.loc[:,onehot.get_feature_names_out()] = answ

In [70]:
import seaborn as sns
df = sns.load_dataset("titanic")
df.who.value_counts()

who
man      537
woman    271
child     83
Name: count, dtype: int64

In [73]:
le = LabelEncoder()

In [74]:
le.fit(df.loc[:,"who"])

LabelEncoder()

In [75]:
ans = le.transform(df.loc[:,"who"])

In [76]:
df.loc[:,"new_who"] = ans

In [77]:
df.new_who.value_counts()

new_who
1    537
2    271
0     83
Name: count, dtype: int64

In [78]:
df

     survived  pclass     sex   age  ...  embark_town  alive  alone new_who
0           0       3    male  22.0  ...  Southampton     no  False       1
1           1       1  female  38.0  ...    Cherbourg    yes  False       2
2           1       3  female  26.0  ...  Southampton    yes   True       2
3           1       1  female  35.0  ...  Southampton    yes  False       2
4           0       3    male  35.0  ...  Southampton     no   True       1
..        ...     ...     ...   ...  ...          ...    ...    ...     ...
886         0       2    male  27.0  ...  Southampton     no   True       1
887         1       1  female  19.0  ...  Southampton    yes   True       2
888         0       3  female   NaN  ...  Southampton     no  False       2
889         1       1    male  26.0  ...    Cherbourg    yes   True       1
890         0       3    male  32.0  ...   Queenstown     no   True       1

[891 rows x 16 columns]