In [112]:
import pandas as pd

In [113]:
df=pd.DataFrame({'Marks':[23,26,29,45,100,130,150,190,550,54,32,11,9,56,900]})
df

    Marks
0      23
1      26
2      29
3      45
4     100
5     130
6     150
7     190
8     550
9      54
10     32
11     11
12      9
13     56
14    900

In [114]:
from sklearn.preprocessing import MinMaxScaler , StandardScaler

In [115]:
minmax = MinMaxScaler(feature_range=(0,5))

In [116]:
minmax.fit_transform(df.loc[:,["Marks"]])

array([[0.07856341],
       [0.09539843],
       [0.11223345],
       [0.2020202 ],
       [0.51066218],
       [0.67901235],
       [0.79124579],
       [1.01571268],
       [3.0359147 ],
       [0.25252525],
       [0.12906846],
       [0.01122334],
       [0.        ],
       [0.2637486 ],
       [5.        ]])

In [117]:
std_scaler = StandardScaler()
# i-mean/std

In [118]:
std_scaler.fit_transform(df.loc[:,["Marks"]])

array([[-0.54725529],
       [-0.53469076],
       [-0.52212622],
       [-0.45511537],
       [-0.22476557],
       [-0.09912022],
       [-0.01535665],
       [ 0.15217048],
       [ 1.65991464],
       [-0.41742177],
       [-0.50956169],
       [-0.59751343],
       [-0.60588979],
       [-0.40904541],
       [ 3.12577703]])

In [119]:
# MinMaxScaler is used when a fixed, bounded range is required for the data, or when the data distribution is not normal. 
# StandardScaler is typically preferred for algorithms that assume a normal distribution or are sensitive to variance

In [120]:
from sklearn.linear_model import LinearRegression
import pandas as pd

In [121]:
data = pd.read_csv("Housing.csv")
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [122]:
data.mainroad= data.mainroad.map({'yes':1,'no':0})
data.guestroom= data.guestroom.map({'yes':1,'no':0})
data.basement= data.basement.map({'yes':1,'no':0})
data.hotwaterheating= data.hotwaterheating.map({'yes':1,'no':0})
data.airconditioning= data.airconditioning.map({'yes':1,'no':0})
data.prefarea= data.prefarea.map({'yes':1,'no':0})

In [123]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [124]:
ans = le.fit_transform(data.loc[:,["furnishingstatus"]])

c:\Users\Nikhal\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [125]:
data["furnishingstatus"]=ans

In [126]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,2
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,2
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,2

In [127]:
from sklearn.model_selection import train_test_split

In [128]:
x = data.iloc[:,1:]
y = data.iloc[:,:1]

In [129]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)

In [131]:
lr = LinearRegression()
lr.fit(x_train,y_train)

LinearRegression()

In [135]:
y_pred = lr.predict(x_test)

In [137]:
from sklearn.metrics import mean_squared_error,r2_score

In [138]:
r2_score(y_test,y_pred)

0.671703216285185